# Generated by Django 5.2.7 on 2025-10-26 21:14

import django.db.models.deletion
import django_models.fields
import django_models.utils.generators
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    django_models.fields.UUIDPrimaryKeyField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="External reference: NF/CTe/Order code",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("recipient_expected", models.CharField(blank=True, max_length=120)),
                ("address", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProofOfDelivery",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            django_models.utils.generators.generate_random_code,
                            *(),
                            **{"length": 8}
                        ),
                        max_length=32,
                        unique=True,
                        verbose_name="Model code",
                    ),
                ),
                (
                    "id",
                    django_models.fields.UUIDPrimaryKeyField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("received_by_name", models.CharField(max_length=120)),
                ("received_by_document", models.CharField(blank=True, max_length=40)),
                (
                    "signed_at",
                    models.DateTimeField(help_text="Client device timestamp"),
                ),
                (
                    "signed_at_server",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Server timestamp (trusted)"
                    ),
                ),
                (
                    "geo_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "geo_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "signature_image",
                    models.URLField(
                        help_text="URL to signature image (e.g., S3 presigned object)"
                    ),
                ),
                (
                    "photos",
                    models.JSONField(
                        default=list,
                        help_text="List of URLs to photos (e.g., S3 objects)",
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        help_text="Metadata (device_id, app_version, etc.)",
                    ),
                ),
                (
                    "delivery",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pod",
                        to="delivery.delivery",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
