# Generated by Django 5.2.7 on 2025-10-29 22:08

import django.db.models.deletion
import django_models.utils.generators
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0001_initial"),
        ("invoice", "0003_alter_invoice_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="delivery",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Delivery",
                "verbose_name_plural": "Deliveries",
            },
        ),
        migrations.AlterModelOptions(
            name="proofofdelivery",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Proof of Delivery",
                "verbose_name_plural": "Proof of Deliveries",
            },
        ),
        migrations.RemoveField(
            model_name="delivery",
            name="address",
        ),
        migrations.AddField(
            model_name="delivery",
            name="invoice",
            field=models.OneToOneField(
                default=123,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deliveries",
                to="invoice.invoice",
                verbose_name="Invoice",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="delivery",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deliveries",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned to",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="code",
            field=models.CharField(
                default=functools.partial(
                    django_models.utils.generators.generate_random_code,
                    *(),
                    **{"length": 8}
                ),
                max_length=32,
                unique=True,
                verbose_name="Model code",
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="recipient_expected",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Recipient Expected"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="delivery",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pod",
                to="delivery.delivery",
                verbose_name="Delivery",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="geo_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Geo Lat",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="geo_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Geo Lng",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="meta",
            field=models.JSONField(
                default=dict,
                help_text="Metadata (device_id, app_version, etc.)",
                verbose_name="Meta",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="photos",
            field=models.JSONField(
                default=list,
                help_text="List of URLs to photos (e.g., S3 objects)",
                verbose_name="Photos",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="received_by_document",
            field=models.CharField(
                blank=True, max_length=40, verbose_name="Received by Document"
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="received_by_name",
            field=models.CharField(max_length=120, verbose_name="Received by"),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="signature_image",
            field=models.URLField(
                help_text="URL to signature image (e.g., S3 presigned object)",
                verbose_name="Signature Image",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="signed_at",
            field=models.DateTimeField(
                help_text="Client device timestamp", verbose_name="Signed at"
            ),
        ),
        migrations.AlterField(
            model_name="proofofdelivery",
            name="signed_at_server",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Server timestamp (trusted)",
                verbose_name="Signed at Server",
            ),
        ),
    ]
