# Generated by Django 5.2.7 on 2025-10-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "delivery",
            "0002_alter_delivery_options_alter_proofofdelivery_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="delivery",
            name="recipient_expected",
        ),
        migrations.AddField(
            model_name="delivery",
            name="observations",
            field=models.TextField(blank=True, default="", verbose_name="Observations"),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
