# Generated by Django 5.2.7 on 2025-10-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0003_remove_delivery_recipient_expected_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="delivery",
            name="delivery_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Delivery at"
            ),
        ),
    ]
