# Generated by Junie to switch POD uploads to ImageField and add related Photo model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0004_delivery_delivery_at"),
    ]

    operations = [
        # Change URLField to ImageField for signature_image
        migrations.AlterField(
            model_name="proofofdelivery",
            name="signature_image",
            field=models.ImageField(blank=True, null=True, upload_to="delivery/signatures/", verbose_name="Signature Image"),
        ),
        # Remove legacy JSON photos field
        migrations.RemoveField(
            model_name="proofofdelivery",
            name="photos",
        ),
        # Create new related model for photos
        migrations.CreateModel(
            name="ProofOfDeliveryPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("image", models.ImageField(upload_to="delivery/photos/", verbose_name="Photo")),
                ("meta", models.JSONField(blank=True, default=dict, verbose_name="Meta")),
                ("pod", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="delivery.proofofdelivery", verbose_name="POD")),
            ],
            options={
                "verbose_name": "POD Photo",
                "verbose_name_plural": "POD Photos",
                "ordering": ["-created_at"],
            },
        ),
    ]
