# Generated by Junie: switch ProofOfDelivery lat/lng to GeoDjango PointField
from django.db import migrations
from django.contrib.gis.db.models.fields import PointField


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0005_pod_imagefield_and_photos_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="proofofdelivery",
            name="location",
            field=PointField(srid=4326, geography=True, null=True, blank=True, verbose_name="Location"),
        ),
        migrations.RemoveField(
            model_name="proofofdelivery",
            name="geo_lat",
        ),
        migrations.RemoveField(
            model_name="proofofdelivery",
            name="geo_lng",
        ),
    ]
