# Generated by Django 5.2.7 on 2025-11-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0007_proofofdeliveryphoto_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proofofdelivery",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
