# Generated by Django 5.2.7 on 2025-11-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0008_proofofdelivery_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proofofdelivery",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivered", "Delivered"),
                    ("failed", "Failed"),
                    ("partial", "Partial"),
                ],
                default="delivered",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
