# Generated by Django 5.2.7 on 2025-11-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0009_alter_proofofdelivery_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="proofofdelivery",
            name="observations",
            field=models.TextField(blank=True, default="", verbose_name="Observations"),
        ),
    ]
