# Generated by Django 5.2.7 on 2025-11-15 18:47

import proj_settings.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("delivery", "0010_proofofdelivery_observations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proofofdelivery",
            name="signature_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=proj_settings.utils.pod_signature_upload_path,
                verbose_name="Signature Image",
            ),
        ),
        migrations.AlterField(
            model_name="proofofdeliveryphoto",
            name="image",
            field=models.ImageField(
                upload_to=proj_settings.utils.pod_photo_upload_path,
                verbose_name="Photo",
            ),
        ),
    ]
