# Generated by Django 5.2.7 on 2025-10-26 21:14

import django.contrib.admin.models
import django_models.fields
import django_models.utils.generators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMTPSettings",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            django_models.utils.generators.generate_random_code,
                            *(),
                            **{"length": 8}
                        ),
                        max_length=32,
                        unique=True,
                        verbose_name="Model code",
                    ),
                ),
                (
                    "id",
                    django_models.fields.UUIDPrimaryKeyField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "host",
                    models.CharField(
                        blank=True,
                        help_text="SMTP server hostname or IP address",
                        max_length=200,
                        verbose_name="Host",
                    ),
                ),
                (
                    "port",
                    models.IntegerField(
                        blank=True,
                        help_text="SMTP server port (usually 587 for TLS or 465 for SSL)",
                        verbose_name="Port",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="Username for SMTP authentication",
                        max_length=128,
                        verbose_name="User",
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        blank=True,
                        help_text="Password for SMTP authentication",
                        max_length=128,
                        verbose_name="Password",
                    ),
                ),
                (
                    "use_tls",
                    models.BooleanField(
                        default=False,
                        help_text="Enable TLS encryption for secure connection",
                        verbose_name="Use TLS",
                    ),
                ),
                (
                    "use_ssl",
                    models.BooleanField(
                        default=False,
                        help_text="Enable SSL encryption for secure connection",
                        verbose_name="Use SSL",
                    ),
                ),
                (
                    "timeout",
                    models.IntegerField(
                        blank=True,
                        default=10,
                        help_text="Connection timeout in seconds",
                        verbose_name="Timeout",
                    ),
                ),
                (
                    "ssl_keyfile",
                    models.FileField(
                        blank=True,
                        help_text="SSL private key file for client certificate authentication",
                        null=True,
                        upload_to="",
                        verbose_name="SSL Keyfile",
                    ),
                ),
                (
                    "ssl_certfile",
                    models.FileField(
                        blank=True,
                        help_text="SSL certificate file for client certificate authentication",
                        null=True,
                        upload_to="",
                        verbose_name="SSL Certfile",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this SMTP configuration is currently active",
                        verbose_name="Active",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Settings",
                "verbose_name_plural": "Email Settings",
            },
        ),
        migrations.CreateModel(
            name="TermsOfService",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            django_models.utils.generators.generate_random_code,
                            *(),
                            **{"length": 8}
                        ),
                        max_length=32,
                        unique=True,
                        verbose_name="Model code",
                    ),
                ),
                (
                    "id",
                    django_models.fields.UUIDPrimaryKeyField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "profile_type",
                    models.CharField(
                        blank=True,
                        choices=[("user", "User"), ("store", "Store")],
                        help_text="Type of profile this terms of service applies to",
                        max_length=18,
                        null=True,
                        verbose_name="Profile Type",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="The actual terms of service content",
                        verbose_name="Terms of Service text",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terms of Service",
                "verbose_name_plural": "Terms of service",
            },
        ),
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "django_admin_log",
                "ordering": ["-action_time"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[
                ("objects", django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
