# Generated by Django 5.2.7 on 2025-11-15 21:42

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="termsofservice",
            name="profile_type",
        ),
        migrations.AddField(
            model_name="termsofservice",
            name="version",
            field=models.PositiveIntegerField(
                blank=True, default=1, verbose_name="Version"
            ),
        ),
        migrations.AlterField(
            model_name="termsofservice",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="The actual terms of service content",
                verbose_name="Terms of Service text",
            ),
        ),
    ]
