# Generated by Django 5.2.7 on 2025-10-26 21:14

import django.db.models.deletion
import django_models.fields
import django_models.utils.generators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            django_models.utils.generators.generate_random_code,
                            *(),
                            **{"length": 8}
                        ),
                        max_length=32,
                        unique=True,
                        verbose_name="Model code",
                    ),
                ),
                (
                    "id",
                    django_models.fields.UUIDPrimaryKeyField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("number", models.CharField(max_length=60)),
                ("series", models.CharField(blank=True, default="", max_length=10)),
                ("issue_date", models.DateField(blank=True, null=True)),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "xml_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/xml/"),
                ),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="invoices/pdf/"),
                ),
                ("status", models.CharField(default="registered", max_length=30)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="company.company",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-created_at"],
                "unique_together": {("company", "number", "series")},
            },
        ),
    ]
