# Generated by Django 5.2.7 on 2025-10-29 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_remove_company_uf_company_address_city_and_more"),
        ("invoice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="address_city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="address_neighborhood",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Neighborhood"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="address_street",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Street"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="address_uf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
                null=True,
                verbose_name="State (UF)",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="company.company",
                verbose_name="Company",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="Issue date"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="number",
            field=models.CharField(max_length=60, verbose_name="Number"),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="invoices/pdf/",
                verbose_name="PDF file",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="series",
            field=models.CharField(
                blank=True, default="", max_length=10, verbose_name="Series"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                default="registered", max_length=30, verbose_name="Status"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Total value"
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="xml_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="invoices/xml/",
                verbose_name="XML file",
            ),
        ),
    ]
