# Generated by Django 5.2.7 on 2025-10-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_invoice_address_city_invoice_address_neighborhood_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={
                "ordering": ["-issue_date", "-created_at"],
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
            },
        ),
    ]
