# Generated by Django 5.2.7 on 2025-10-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0003_alter_invoice_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="key",
            field=models.CharField(default=123123, max_length=50, verbose_name="Key"),
            preserve_default=False,
        ),
    ]
