# Generated by Django 5.2.7 on 2025-10-29 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0005_invoice_address_number_invoice_address_zip_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="recipient_address_city",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recipient_address_neighborhood",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Neighborhood"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recipient_address_number",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Number"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recipient_address_street",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Street"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recipient_address_uf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                default="",
                max_length=2,
                verbose_name="State (UF)",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recipient_address_zip_code",
            field=models.CharField(
                blank=True, default="", max_length=12, verbose_name="Zip Code"
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recipient_name",
            field=models.CharField(
                default=1, max_length=500, verbose_name="Recipient Name"
            ),
            preserve_default=False,
        ),
    ]
