# Generated by Junie to drop legacy address_* columns that are no longer in the model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0006_invoice_recipient_address_city_and_more"),
    ]

    operations = [
        # These fields were introduced in 0002 and 0005 but later replaced by
        # the recipient_address_* fields. Keeping them (especially with NOT NULL)
        # causes INSERTs to fail since the ORM no longer supplies values.
        migrations.RemoveField(
            model_name="invoice",
            name="address_city",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="address_neighborhood",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="address_street",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="address_number",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="address_uf",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="address_zip_code",
        ),
    ]
