# Generated by Django 5.2.7 on 2025-11-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0007_remove_legacy_address_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, upload_to="invoices/pdf/", verbose_name="DANFE"
            ),
        ),
    ]
