# Generated by Django 5.2.7 on 2025-10-26 21:14

import django_models.fields
import django_models.utils.generators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "code",
                    models.CharField(
                        default=functools.partial(
                            django_models.utils.generators.generate_random_code,
                            *(),
                            **{"length": 8}
                        ),
                        max_length=32,
                        unique=True,
                        verbose_name="Model code",
                    ),
                ),
                (
                    "id",
                    django_models.fields.UUIDPrimaryKeyField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(help_text="Nome fantasia", max_length=500)),
                (
                    "legal_name",
                    models.CharField(help_text="Razão social", max_length=500),
                ),
                ("cnpj", models.CharField(max_length=32, unique=True)),
                (
                    "certificate",
                    models.FileField(blank=True, null=True, upload_to="certificates/"),
                ),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
    ]
