# Generated by Django 5.2.7 on 2025-10-26 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="certificate_expires_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Certificate expiration"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="certificate_password",
            field=models.CharField(
                blank=True,
                help_text="Senha do arquivo do certificado digital",
                max_length=255,
                null=True,
                verbose_name="Certificate password",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="certificate_serial",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Certificate serial number",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="csc_id",
            field=models.CharField(
                blank=True,
                help_text="Apenas para NFC-e (id do Código de Segurança do Contribuinte)",
                max_length=16,
                null=True,
                verbose_name="CSC ID",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="csc_token",
            field=models.CharField(
                blank=True,
                help_text="Apenas para NFC-e (token do Código de Segurança do Contribuinte)",
                max_length=128,
                null=True,
                verbose_name="CSC token",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="enable_sefaz_sync",
            field=models.BooleanField(default=True, verbose_name="Enable SEFAZ sync"),
        ),
        migrations.AddField(
            model_name="company",
            name="inscricao_estadual",
            field=models.CharField(
                blank=True,
                max_length=32,
                null=True,
                verbose_name="State registration (IE)",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="last_nsu",
            field=models.BigIntegerField(
                default=0,
                help_text="Último NSU processado para distribuição de DF-e",
                verbose_name="Last NSU",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="last_nsu_updated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Last NSU updated at"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="sefaz_environment",
            field=models.CharField(
                choices=[
                    ("production", "Production"),
                    ("homologation", "Homologation"),
                ],
                default="production",
                max_length=16,
                verbose_name="SEFAZ environment",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="uf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
                null=True,
                verbose_name="State (UF)",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="certificate",
            field=models.FileField(
                blank=True,
                help_text="Arquivo .pfx/.p12 do certificado e-CNPJ (A1)",
                null=True,
                upload_to="certificates/",
                verbose_name="Digital certificate (A1)",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="cnpj",
            field=models.CharField(max_length=32, unique=True, verbose_name="CNPJ"),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_name",
            field=models.CharField(
                help_text="Razão social", max_length=500, verbose_name="Legal name"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text="Nome fantasia", max_length=500, verbose_name="Trade name"
            ),
        ),
    ]
