# Generated by Django 5.2.7 on 2025-10-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_company_certificate_expires_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={
                "ordering": ["name"],
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Is Active"),
        ),
        migrations.AlterField(
            model_name="company",
            name="certificate",
            field=models.FileField(
                blank=True,
                help_text="e-CNPJ (A1) certificate file (.pfx/.p12)",
                null=True,
                upload_to="certificates/",
                verbose_name="Digital certificate (A1)",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="certificate_password",
            field=models.CharField(
                blank=True,
                help_text="Password for the digital certificate file",
                max_length=255,
                null=True,
                verbose_name="Certificate password",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="csc_id",
            field=models.CharField(
                blank=True,
                help_text="NFC-e only (Taxpayer Security Code ID)",
                max_length=16,
                null=True,
                verbose_name="CSC ID",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="csc_token",
            field=models.CharField(
                blank=True,
                help_text="NFC-e only (Taxpayer Security Code token)",
                max_length=128,
                null=True,
                verbose_name="CSC token",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="last_nsu",
            field=models.BigIntegerField(
                default=0,
                help_text="Last processed NSU for DF-e distribution",
                verbose_name="Last NSU",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_name",
            field=models.CharField(
                help_text="Registered legal name",
                max_length=500,
                verbose_name="Legal name",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                help_text="Public/commercial trade name",
                max_length=500,
                verbose_name="Trade name",
            ),
        ),
    ]
