# Generated by Django 5.2.7 on 2025-10-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_options_company_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="uf",
        ),
        migrations.AddField(
            model_name="company",
            name="address_city",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="address_neighborhood",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Neighborhood"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="address_street",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Street"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="address_uf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "AC"),
                    ("AL", "AL"),
                    ("AP", "AP"),
                    ("AM", "AM"),
                    ("BA", "BA"),
                    ("CE", "CE"),
                    ("DF", "DF"),
                    ("ES", "ES"),
                    ("GO", "GO"),
                    ("MA", "MA"),
                    ("MT", "MT"),
                    ("MS", "MS"),
                    ("MG", "MG"),
                    ("PA", "PA"),
                    ("PB", "PB"),
                    ("PR", "PR"),
                    ("PE", "PE"),
                    ("PI", "PI"),
                    ("RJ", "RJ"),
                    ("RN", "RN"),
                    ("RS", "RS"),
                    ("RO", "RO"),
                    ("RR", "RR"),
                    ("SC", "SC"),
                    ("SP", "SP"),
                    ("SE", "SE"),
                    ("TO", "TO"),
                ],
                max_length=2,
                null=True,
                verbose_name="State (UF)",
            ),
        ),
    ]
