# Generated by Django 5.2.7 on 2025-11-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_company_address_number_company_address_zip_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address_complement",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Complement"
            ),
        ),
    ]
