# Generated by Django 5.2.7 on 2025-11-15 18:47

import proj_settings.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0006_company_address_complement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="certificate",
            field=models.FileField(
                blank=True,
                help_text="e-CNPJ (A1) certificate file (.pfx/.p12)",
                null=True,
                upload_to=proj_settings.utils.certificates_upload_path,
                verbose_name="Digital certificate (A1)",
            ),
        ),
    ]
