# Generated by Django 5.2.7 on 2025-11-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_customgroup_alter_user_managers_alter_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("pt-br", "Portuguese (Brazil)"),
                    ("es", "Spanish"),
                ],
                default="en",
                max_length=10,
                verbose_name="Preferred Language",
            ),
        ),
    ]
